# serverless.yml FINAL
org: pcasaverde
service: calificador-leads-api



provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev
  memorySize: 1024
  timeout: 20
  httpApi:
    cors: true
  iam:
    role: arn:aws:iam::013960419123:role/LabRole
  environment:
    LEADS_TABLE_NAME: leadsTable

functions:
  processLead:
    handler: handler.main
    events:
      - httpApi:
          path: /leads
          method: post

resources:
  Resources:
    leadsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: leadsTable
        AttributeDefinitions:
          - AttributeName: leadId
            AttributeType: S
        KeySchema:
          - AttributeName: leadId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    LeadFrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: calificador-leads-frontend-${sls:stage}-${aws:accountId}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
        # AÑADIR ESTE BLOQUE COMPLETO para permitir que el bucket sea público.
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
          
    LeadFrontendBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref LeadFrontendBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: !Join [ "/", [ !GetAtt LeadFrontendBucket.Arn, "*" ] ]